source ~/.vim/rc/settings.vim
source ~/.vim/rc/plugins.vim
source ~/.vim/rc/plugin-settings.vim
source ~/.vim/rc/styling.vim
source ~/.vim/rc/formatting.vim
source ~/.vim/rc/completion-menu.vim
source ~/.vim/rc/search.vim
source ~/.vim/rc/mappings.vim
source ~/.vim/rc/commands.vim
source ~/.vim/rc/validations.vim
